Create filter_in_new_panel
3liz/lizmap-javascript-scripts pull request #23
Opened 2020-05-08 12:42 UTC by tethysgeco

See the TOC and filter at the same time, moving filter in a new panel.

2020-07-01 07:26 UTC, Gustry commented
Thanks for your contributions @tethysgeco 
You file would need to be a folder, like the current folder organization and a link in the readme.
I have created the https://github.com/3liz/lizmap-javascript-scripts/blob/master/CONTRIBUTING.md to help you.
Is-it OK?

2022-04-06 15:07 UTC, Gustry reviewed
Thanks for your contribution !

2022-04-06 15:07 UTC, Gustry commented on library/ui/move_filter_in_new_panel/README.md
> +![example image](https://github.com/tethysgeco/lizmap-javascript-scripts/blob/patch-1/library/ui/move_filter_in_new_panel/image.jpg?raw=true)
```suggestion
![example image](./image.jpg)
```

So this will use the image the correct repository

2022-04-07 10:31 UTC, nboisteault requested changes
Thanks @tethysgeco !
Could you replace `Filtra dati` by `Filter`. We use English by default, people will then translate or add an icon if they prefer.

2022-04-07 10:31 UTC, nboisteault commented on library/ui/move_filter_in_new_panel/filter_in_new_panel.js
> +            $('#switcher-layers-actions').append('<button class="btn-custom" id="custom-filter-switcher" style="outline: none;background: rgba(255,255,255,0.9); border-radius: 3px;color: black; margi
```suggestion
            $('#switcher-layers-actions').append('<button class="btn-custom" id="custom-filter-switcher" style="outline: none;background: rgba(255,255,255,0.9); border-radius: 3px;color: black; margin: 8px; margin-right: 0px;">Filter</button>');
```

2022-04-07 12:25 UTC, tethysgeco commented
We made the requested changes.

2022-04-07 12:27 UTC, merged

2022-04-07 12:27 UTC, nboisteault commented
@tethysgeco thanks!